/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsString,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { Club } from "../../club/base/Club";
import { CourseRating } from "../../courseRating/base/CourseRating";
import { CourseTeetype } from "../../courseTeetype/base/CourseTeetype";
import { SeasonCourse } from "../../seasonCourse/base/SeasonCourse";
import { Tee } from "../../tee/base/Tee";

@ObjectType()
class Course {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  id!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  courseName!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt!: Date | null;

  @ApiProperty({
    required: true,
    type: () => Club,
  })
  @ValidateNested()
  @Type(() => Club)
  club?: Club;

  @ApiProperty({
    required: false,
    type: () => [CourseRating],
  })
  @ValidateNested()
  @Type(() => CourseRating)
  @IsOptional()
  courseRating?: Array<CourseRating>;

  @ApiProperty({
    required: false,
    type: () => [CourseTeetype],
  })
  @ValidateNested()
  @Type(() => CourseTeetype)
  @IsOptional()
  courseTeetype?: Array<CourseTeetype>;

  @ApiProperty({
    required: false,
    type: () => [SeasonCourse],
  })
  @ValidateNested()
  @Type(() => SeasonCourse)
  @IsOptional()
  seasonCourse?: Array<SeasonCourse>;

  @ApiProperty({
    required: false,
    type: () => [Tee],
  })
  @ValidateNested()
  @Type(() => Tee)
  @IsOptional()
  tee?: Array<Tee>;
}

export { Course as Course };
