/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ScoreService } from "../score.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ScoreCreateInput } from "./ScoreCreateInput";
import { ScoreWhereInput } from "./ScoreWhereInput";
import { ScoreWhereUniqueInput } from "./ScoreWhereUniqueInput";
import { ScoreFindManyArgs } from "./ScoreFindManyArgs";
import { ScoreUpdateInput } from "./ScoreUpdateInput";
import { Score } from "./Score";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScoreControllerBase {
  constructor(
    protected readonly service: ScoreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Score })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: ScoreCreateInput): Promise<Score> {
    return await this.service.create({
      data: {
        ...data,

        members: {
          connect: data.members,
        },

        schedule: {
          connect: data.schedule,
        },
      },
      select: {
        id: true,
        lastname: true,
        firstname: true,
        scoreDate: true,
        h1: true,
        h2: true,
        h3: true,
        h4: true,
        h5: true,
        h6: true,
        h7: true,
        h8: true,
        h9: true,
        front: true,
        fhndcp: true,
        fnet: true,
        ninePlayed: true,
        press: true,
        h10: true,
        h11: true,
        h12: true,
        h13: true,
        h14: true,
        h15: true,
        h16: true,
        h17: true,
        h18: true,
        back: true,
        bhndcp: true,
        bnet: true,
        createdAt: true,
        updatedAt: true,

        members: {
          select: {
            id: true,
          },
        },

        schedule: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Score] })
  @ApiNestedQuery(ScoreFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Score[]> {
    const args = plainToClass(ScoreFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        lastname: true,
        firstname: true,
        scoreDate: true,
        h1: true,
        h2: true,
        h3: true,
        h4: true,
        h5: true,
        h6: true,
        h7: true,
        h8: true,
        h9: true,
        front: true,
        fhndcp: true,
        fnet: true,
        ninePlayed: true,
        press: true,
        h10: true,
        h11: true,
        h12: true,
        h13: true,
        h14: true,
        h15: true,
        h16: true,
        h17: true,
        h18: true,
        back: true,
        bhndcp: true,
        bnet: true,
        createdAt: true,
        updatedAt: true,

        members: {
          select: {
            id: true,
          },
        },

        schedule: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Score })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ScoreWhereUniqueInput
  ): Promise<Score | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        lastname: true,
        firstname: true,
        scoreDate: true,
        h1: true,
        h2: true,
        h3: true,
        h4: true,
        h5: true,
        h6: true,
        h7: true,
        h8: true,
        h9: true,
        front: true,
        fhndcp: true,
        fnet: true,
        ninePlayed: true,
        press: true,
        h10: true,
        h11: true,
        h12: true,
        h13: true,
        h14: true,
        h15: true,
        h16: true,
        h17: true,
        h18: true,
        back: true,
        bhndcp: true,
        bnet: true,
        createdAt: true,
        updatedAt: true,

        members: {
          select: {
            id: true,
          },
        },

        schedule: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Score })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ScoreWhereUniqueInput,
    @common.Body() data: ScoreUpdateInput
  ): Promise<Score | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          members: {
            connect: data.members,
          },

          schedule: {
            connect: data.schedule,
          },
        },
        select: {
          id: true,
          lastname: true,
          firstname: true,
          scoreDate: true,
          h1: true,
          h2: true,
          h3: true,
          h4: true,
          h5: true,
          h6: true,
          h7: true,
          h8: true,
          h9: true,
          front: true,
          fhndcp: true,
          fnet: true,
          ninePlayed: true,
          press: true,
          h10: true,
          h11: true,
          h12: true,
          h13: true,
          h14: true,
          h15: true,
          h16: true,
          h17: true,
          h18: true,
          back: true,
          bhndcp: true,
          bnet: true,
          createdAt: true,
          updatedAt: true,

          members: {
            select: {
              id: true,
            },
          },

          schedule: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Score })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ScoreWhereUniqueInput
  ): Promise<Score | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          lastname: true,
          firstname: true,
          scoreDate: true,
          h1: true,
          h2: true,
          h3: true,
          h4: true,
          h5: true,
          h6: true,
          h7: true,
          h8: true,
          h9: true,
          front: true,
          fhndcp: true,
          fnet: true,
          ninePlayed: true,
          press: true,
          h10: true,
          h11: true,
          h12: true,
          h13: true,
          h14: true,
          h15: true,
          h16: true,
          h17: true,
          h18: true,
          back: true,
          bhndcp: true,
          bnet: true,
          createdAt: true,
          updatedAt: true,

          members: {
            select: {
              id: true,
            },
          },

          schedule: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
