/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourseRatingService } from "../courseRating.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourseRatingCreateInput } from "./CourseRatingCreateInput";
import { CourseRatingWhereInput } from "./CourseRatingWhereInput";
import { CourseRatingWhereUniqueInput } from "./CourseRatingWhereUniqueInput";
import { CourseRatingFindManyArgs } from "./CourseRatingFindManyArgs";
import { CourseRatingUpdateInput } from "./CourseRatingUpdateInput";
import { CourseRating } from "./CourseRating";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourseRatingControllerBase {
  constructor(
    protected readonly service: CourseRatingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourseRating })
  @nestAccessControl.UseRoles({
    resource: "CourseRating",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: CourseRatingCreateInput
  ): Promise<CourseRating> {
    return await this.service.create({
      data: {
        ...data,

        course: {
          connect: data.course,
        },
      },
      select: {
        id: true,
        tee: true,
        courseSlope: true,
        courseRating: true,
        coursePar: true,
        frontSlope: true,
        frontRating: true,
        frontPar: true,
        backSlope: true,
        backRating: true,
        backPar: true,
        createdAt: true,
        updatedAt: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CourseRating] })
  @ApiNestedQuery(CourseRatingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseRating",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<CourseRating[]> {
    const args = plainToClass(CourseRatingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        tee: true,
        courseSlope: true,
        courseRating: true,
        coursePar: true,
        frontSlope: true,
        frontRating: true,
        frontPar: true,
        backSlope: true,
        backRating: true,
        backPar: true,
        createdAt: true,
        updatedAt: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourseRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseRating",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CourseRatingWhereUniqueInput
  ): Promise<CourseRating | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        tee: true,
        courseSlope: true,
        courseRating: true,
        coursePar: true,
        frontSlope: true,
        frontRating: true,
        frontPar: true,
        backSlope: true,
        backRating: true,
        backPar: true,
        createdAt: true,
        updatedAt: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourseRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseRating",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CourseRatingWhereUniqueInput,
    @common.Body() data: CourseRatingUpdateInput
  ): Promise<CourseRating | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },
        },
        select: {
          id: true,
          tee: true,
          courseSlope: true,
          courseRating: true,
          coursePar: true,
          frontSlope: true,
          frontRating: true,
          frontPar: true,
          backSlope: true,
          backRating: true,
          backPar: true,
          createdAt: true,
          updatedAt: true,

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourseRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseRating",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CourseRatingWhereUniqueInput
  ): Promise<CourseRating | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          tee: true,
          courseSlope: true,
          courseRating: true,
          coursePar: true,
          frontSlope: true,
          frontRating: true,
          frontPar: true,
          backSlope: true,
          backRating: true,
          backPar: true,
          createdAt: true,
          updatedAt: true,

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
